# Generated by Django 5.2.8 on 2025-11-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='external_id',
            new_name='user_id',
        ),
    ]
