# Generated by Django 5.2.8 on 2025-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_external_id_userprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
