from django.urls import path

from .views import (
    AcademicLeaveCreateView,
    AcademicLeaveListView,
    AccessControlIngestView,
    AdmissionsInquiryView,
    AuthMeView,
    LoginView,
    LogoutView,
    UserSettingsView,
    CareerConsultationCreateView,
    CareerConsultationListView,
    CareerVacancyApplyView,
    CareerVacancyDetailView,
    CareerVacancyListView,
    DashboardSnapshotView,
    DeaneryCertificateCreateView,
    DeaneryCertificateListView,
    DeaneryCompensationCreateView,
    DeaneryTransferCreateView,
    DormGuestPassCreateView,
    DormGuestPassListView,
    DormPaymentIntentCreateView,
    DormPaymentIntentListView,
    DormServiceOrderCreateView,
    DormServiceOrderListView,
    DormServicesListView,
    DormSupportTicketCreateView,
    DormSupportTicketListView,
    ElectiveCatalogView,
    ElectiveEnrollmentCreateView,
    ElectiveEnrollmentListView,
    EventDetailView,
    EventRegistrationCreateView,
    EventRegistrationsMyView,
    EventsListView,
    HRLeaveRequestCreateView,
    HRLeaveRequestListView,
    HRTravelRequestCreateView,
    HRTravelRequestListView,
    LibraryCatalogView,
    LibraryEBookAccessCreateView,
    LibraryEBookAccessListView,
    LibraryFinePaymentIntentCreateView,
    LibraryFinePaymentIntentListView,
    LibraryHoldCreateView,
    LibraryHoldListView,
    LibraryLoanCreateView,
    LibraryLoansListView,
    MaxBotWebhookView,
    NewsMentionsView,
    OfficeCertificateCreateView,
    OfficeGuestPassCreateView,
    OfficeGuestPassListView,
    OpenDayListView,
    OpenDayRegistrationView,
    PaymentWebhookView,
    ProgramDetailView,
    ProgramListView,
    ProgramRequirementView,
    ProjectApplyView,
    ProjectDetailView,
    ProjectListView,
    ProjectSubscriptionsView,
    ProjectTasksView,
    ProjectTeamView,
    ScheduleGroupView,
    ScheduleMyView,
    TeacherFeedbackView,
    TrackerWebhookView,
    TuitionInvoiceListView,
    TuitionPaymentIntentCreateView,
    UniversityDetailView,
    UniversityListView,
)

from .views.deanery import (
    AcademicLeaveCreateView,
    AcademicLeaveListView,
    DeaneryCertificateCreateView,
    DeaneryCertificateListView,
    DeaneryCompensationCreateView,
    DeaneryTransferCreateView,
    TuitionInvoiceListView,
    TuitionPaymentIntentCreateView,
    DeaneryTuitionInvoiceCreateView,
    TuitionPaymentIntentListView,
    DeaneryCompensationListView,
    DeaneryTransferListView,
)

urlpatterns = [
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("users/settings", UserSettingsView.as_view(), name="user-settings"),
    path("admissions/universities", UniversityListView.as_view(), name="admissions-universities"),
    path("admissions/universities/<str:id>", UniversityDetailView.as_view(), name="admissions-university-detail"),
    path("admissions/programs", ProgramListView.as_view(), name="admissions-programs"),
    path("admissions/programs/<str:id>", ProgramDetailView.as_view(), name="admissions-program-detail"),
    path("admissions/requirements", ProgramRequirementView.as_view(), name="admissions-requirements"),
    path("admissions/open-days", OpenDayListView.as_view(), name="admissions-open-days"),
    path("admissions/open-days/registrations", OpenDayRegistrationView.as_view(), name="admissions-open-day-register"),
    path("admissions/inquiries", AdmissionsInquiryView.as_view(), name="admissions-inquiries"),

    path("schedule/my", ScheduleMyView.as_view(), name="schedule-my"),
    path("schedule/groups/<str:group_id>", ScheduleGroupView.as_view(), name="schedule-group"),
    path("feedback/teachers", TeacherFeedbackView.as_view(), name="feedback-teachers"),
    path("electives/catalog", ElectiveCatalogView.as_view(), name="electives-catalog"),
    path("electives/enrollments", ElectiveEnrollmentCreateView.as_view(), name="electives-enroll"),
    path("electives/enrollments/my", ElectiveEnrollmentListView.as_view(), name="electives-enrollments-my"),

    path("projects", ProjectListView.as_view(), name="projects"),
    path("projects/<uuid:id>", ProjectDetailView.as_view(), name="projects-detail"),
    path("projects/<uuid:project_id>/apply", ProjectApplyView.as_view(), name="projects-apply"),
    path("projects/<uuid:project_id>/team", ProjectTeamView.as_view(), name="projects-team"),
    path("projects/<uuid:project_id>/tasks", ProjectTasksView.as_view(), name="projects-tasks"),
    path("projects/<uuid:project_id>/subscriptions", ProjectSubscriptionsView.as_view(), name="projects-subscriptions"),

    path("careers/vacancies", CareerVacancyListView.as_view(), name="careers-vacancies"),
    path("careers/vacancies/<str:id>", CareerVacancyDetailView.as_view(), name="careers-vacancy-detail"),
    path("careers/vacancies/<str:vacancy_id>/apply", CareerVacancyApplyView.as_view(), name="careers-vacancy-apply"),
    path("careers/consultations", CareerConsultationCreateView.as_view(), name="careers-consultations-create"),
    path("careers/consultations/my", CareerConsultationListView.as_view(), name="careers-consultations-my"),

    path("deanery/certificates", DeaneryCertificateCreateView.as_view(), name="deanery-certificates-create"),
    path("deanery/certificates/my", DeaneryCertificateListView.as_view(), name="deanery-certificates-my"),
    path("deanery/payments/tuition/intents", TuitionPaymentIntentCreateView.as_view(), name="deanery-payments-intents"),
    path("deanery/payments/tuition/intents/list", TuitionPaymentIntentListView.as_view(), name="deanery-payments-intents-list"),
    path("deanery/payments/tuition/create", DeaneryTuitionInvoiceCreateView.as_view(), name="deanery-payments-create"),
    path("deanery/payments/tuition", TuitionInvoiceListView.as_view(), name="deanery-payments"),
    path("deanery/compensations", DeaneryCompensationCreateView.as_view(), name="deanery-compensations"),
    path("deanery/compensations/list", DeaneryCompensationListView.as_view(), name="deanery-compensations-list"),
    path("deanery/transfer-requests", DeaneryTransferCreateView.as_view(), name="deanery-transfer"),
    path("deanery/transfer-requests/list", DeaneryTransferListView.as_view(), name="deanery-transfer-list"),
    path("deanery/academic-leave", AcademicLeaveCreateView.as_view(), name="deanery-academic-leave"),
    path("deanery/academic-leave/my", AcademicLeaveListView.as_view(), name="deanery-academic-leave-my"),

    path("dorm/payments/intents", DormPaymentIntentCreateView.as_view(), name="dorm-payment-intents"),
    path("dorm/payments/intents/list", DormPaymentIntentListView.as_view(), name="dorm-payment-intents-list"),
    path("dorm/services", DormServicesListView.as_view(), name="dorm-services"),
    path("dorm/services/orders", DormServiceOrderCreateView.as_view(), name="dorm-service-order"),
    path("dorm/services/orders/list", DormServiceOrderListView.as_view(), name="dorm-service-order-list"),
    path("dorm/guests/passes", DormGuestPassCreateView.as_view(), name="dorm-guest-pass"),
    path("dorm/guests/passes/list", DormGuestPassListView.as_view(), name="dorm-guest-pass-list"),
    path("dorm/support/tickets", DormSupportTicketCreateView.as_view(), name="dorm-support-ticket"),
    path("dorm/support/tickets/my", DormSupportTicketListView.as_view(), name="dorm-support-ticket-my"),

    path("events", EventsListView.as_view(), name="events-list"),
    path("events/my", EventRegistrationsMyView.as_view(), name="events-my"),
    path("events/<str:id>", EventDetailView.as_view(), name="events-detail"),
    path("events/<str:event_id>/registrations", EventRegistrationCreateView.as_view(), name="events-register"),

    path("library/catalog", LibraryCatalogView.as_view(), name="library-catalog"),
    path("library/holds", LibraryHoldCreateView.as_view(), name="library-holds-create"),
    path("library/holds/my", LibraryHoldListView.as_view(), name="library-holds-my"),
    path("library/loans", LibraryLoanCreateView.as_view(), name="library-loans-create"),
    path("library/loans/my", LibraryLoansListView.as_view(), name="library-loans-my"),
    path("library/ebooks/access", LibraryEBookAccessListView.as_view(), name="library-ebooks-access"),
    path("library/ebooks/access/create", LibraryEBookAccessCreateView.as_view(), name="library-ebooks-access-create"),
    path("library/fines/payments/intents", LibraryFinePaymentIntentCreateView.as_view(), name="library-fines-intents"),
    path("library/fines/payments/intents/list", LibraryFinePaymentIntentListView.as_view(), name="library-fines-intents-list"),

    path("hr/travel/requests", HRTravelRequestCreateView.as_view(), name="hr-travel-create"),
    path("hr/travel/requests/my", HRTravelRequestListView.as_view(), name="hr-travel-my"),
    path("hr/leave/requests", HRLeaveRequestCreateView.as_view(), name="hr-leave-create"),
    path("hr/leave/requests/my", HRLeaveRequestListView.as_view(), name="hr-leave-my"),
    path("hr/certificates", OfficeCertificateCreateView.as_view(), name="hr-certificates"),
    path("office/guest-passes", OfficeGuestPassCreateView.as_view(), name="office-guest-pass"),
    path("office/guest-passes/my", OfficeGuestPassListView.as_view(), name="office-guest-pass-my"),

    path("dashboards/snapshots", DashboardSnapshotView.as_view(), name="dashboards-snapshots"),
    path("news/mentions", NewsMentionsView.as_view(), name="news-mentions"),

    path("integrations/access-control/ingest", AccessControlIngestView.as_view(), name="integrations-ac"),
    path("integrations/tracker/webhook", TrackerWebhookView.as_view(), name="integrations-tracker"),
    path("integrations/payments/webhook", PaymentWebhookView.as_view(), name="integrations-payments"),
    path("integrations/max/webhook", MaxBotWebhookView.as_view(), name="integrations-max"),
]

